name: Build DoomMC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install CMake 4.2
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v4.2.0/cmake-4.2.0-linux-x86_64.sh
          sudo mkdir -p /opt/cmake
          sudo sh cmake-4.2.0-linux-x86_64.sh --prefix=/opt/cmake --skip-license
          sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
          cmake --version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate sources
        run: ./gradlew genSources
        
      - name: Package .gradle as ZIP
        run: zip -r build/DoomMC-sources.zip build
        
      - name: Upload DoomMC sources ZIP
        uses: actions/upload-artifact@v4
        with:
          name: DoomMC-sources
          path: build/DoomMC-sources.zip

      - name: Build DoomMC
        run: ./gradlew build

      - name: Upload DoomMC JAR
        uses: actions/upload-artifact@v4
        with:
          name: DoomMC-JAR
          path: build/libs/*.jar
