name: Build DoomMC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate sources
        run: ./gradlew genSources

      - name: Build DoomMC
        run: ./gradlew build

      - name: Package sources as ZIP
        run: zip -r build/libs/DoomMC-sources.zip build/generated/sources

      - name: Upload DoomMC JAR
        uses: actions/upload-artifact@v4
        with:
          name: DoomMC-JAR
          path: build/libs/*.jar

      - name: Upload DoomMC sources ZIP
        uses: actions/upload-artifact@v4
        with:
          name: DoomMC-sources
          path: build/libs/DoomMC-sources.zip
