name: Build DoomMC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install CMake 4.2
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v4.2.0/cmake-4.2.0-linux-x86_64.sh
          sudo mkdir -p /opt/cmake
          sudo sh cmake-4.2.0-linux-x86_64.sh --prefix=/opt/cmake --skip-license
          sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
          cmake --version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build DoomMC
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DoomMC-Build
          path: |
            build/libs/*.jar
            build/dist/arm64/libdoomjni.so
